/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TransferFinalizeDisableOTP type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransferFinalizeDisableOTP{}

// TransferFinalizeDisableOTP struct for TransferFinalizeDisableOTP
type TransferFinalizeDisableOTP struct {
	// OTP sent to business phone to verify disabling OTP requirement
	Otp string `json:"otp"`
}

type _TransferFinalizeDisableOTP TransferFinalizeDisableOTP

// NewTransferFinalizeDisableOTP instantiates a new TransferFinalizeDisableOTP object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferFinalizeDisableOTP(otp string) *TransferFinalizeDisableOTP {
	this := TransferFinalizeDisableOTP{}
	this.Otp = otp
	return &this
}

// NewTransferFinalizeDisableOTPWithDefaults instantiates a new TransferFinalizeDisableOTP object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferFinalizeDisableOTPWithDefaults() *TransferFinalizeDisableOTP {
	this := TransferFinalizeDisableOTP{}
	return &this
}

// GetOtp returns the Otp field value
func (o *TransferFinalizeDisableOTP) GetOtp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Otp
}

// GetOtpOk returns a tuple with the Otp field value
// and a boolean to check if the value has been set.
func (o *TransferFinalizeDisableOTP) GetOtpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Otp, true
}

// SetOtp sets field value
func (o *TransferFinalizeDisableOTP) SetOtp(v string) {
	o.Otp = v
}

func (o TransferFinalizeDisableOTP) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransferFinalizeDisableOTP) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["otp"] = o.Otp
	return toSerialize, nil
}

func (o *TransferFinalizeDisableOTP) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"otp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransferFinalizeDisableOTP := _TransferFinalizeDisableOTP{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransferFinalizeDisableOTP)

	if err != nil {
		return err
	}

	*o = TransferFinalizeDisableOTP(varTransferFinalizeDisableOTP)

	return err
}

type NullableTransferFinalizeDisableOTP struct {
	value *TransferFinalizeDisableOTP
	isSet bool
}

func (v NullableTransferFinalizeDisableOTP) Get() *TransferFinalizeDisableOTP {
	return v.value
}

func (v *NullableTransferFinalizeDisableOTP) Set(val *TransferFinalizeDisableOTP) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferFinalizeDisableOTP) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferFinalizeDisableOTP) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferFinalizeDisableOTP(val *TransferFinalizeDisableOTP) *NullableTransferFinalizeDisableOTP {
	return &NullableTransferFinalizeDisableOTP{value: val, isSet: true}
}

func (v NullableTransferFinalizeDisableOTP) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferFinalizeDisableOTP) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


